### PR TITLE
Multi-target .NET Standard 2.0, .NET Core App 3.1 and .NET 5.0

### PR DESCRIPTION
**Pull request by silkfire**
PR for issue #24

### CODE REVIEW

**Comment by silkfire** [comment]
The CI pipeline failed because the environment uses the old version of MSBuild (16.7.0) whereas .NET 5 requires v16.8.0.

**Comment by ipjohnson** [comment]
I looked at this and it's good but as you pointed the build pipeline doesn't support 16.8.0 yet. Looking at [appveyor updates](https://www.appveyor.com/updates/) I think it will be the end of this month that they do a release. I can merge it in then.

**Comment by silkfire** [comment]
Hey Ian, that's totally fine with me. I appreciate that you took the time to look into this PR. 😊

**Comment by ipjohnson** [comment]
appveyor has updated their image and I'll pull this in before thanksgiving.

**Comment by silkfire** [comment]
Fantastic news :)

**Comment by silkfire** [comment]
@ipjohnson Will you be pushing a new release to NuGet soonish?

**Comment by ipjohnson** [comment]
@silkfire sorry forgot to update the ticket, I pushed an [RC version](https://www.nuget.org/packages/Grace.DependencyInjection.Extensions/7.1.0-RC121) to nuget for testing when I merged this.

**Comment by silkfire** [comment]
I did realize that yes. How long will it be in RC?

**Comment by ipjohnson** [comment]
released

**Pull request merged**
